CREATE TABLE `quiz` (
  `id` CHAR(36) PRIMARY KEY,
  `title` VARCHAR(50) NOT NULL,
  `creator` VARCHAR(30) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);