CREATE TABLE `user` (
  `id` CHAR(36) PRIMARY KEY,
  `username` VARCHAR(16) UNIQUE NOT NULL,
  `password` CHAR(60) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);